MERGE INTO `gcp-project.HRA_CORE_V.EXPERIENCE` AS A
USING (
  SELECT
    A.CANDIDATE_ID,
    MAX(A.SRC_FILE_DTTM) AS MAX_SRC_FILE_DTTM
  FROM
    `gcp-project.HRA_CORE_V.EXPERIENCE` AS A
  WHERE
    A.CANDIDATE_ID IN (
      SELECT
        CANDIDATE_ID
      FROM
        `gcp-project.HRA_CORE_V.EXPERIENCE`
      GROUP BY
        CANDIDATE_ID
      HAVING
        COUNT(DISTINCT MOST_RCNT_IND) > 1
    )
  GROUP BY
    1
) AS B
ON A.CANDIDATE_ID = B.CANDIDATE_ID
WHEN MATCHED AND A.CURR_IND = 'Y' AND A.MOST_RCNT_IND = 'no' THEN
UPDATE
SET
  CURR_IND = 'N',
  EFF_END_DTTM = TIMESTAMP_SUB(B.MAX_SRC_FILE_DTTM, INTERVAL 1 MICROSECOND),
  UPDT_PRCS_ID = (
    SELECT
      ProcessID
    FROM
      `gcp-project.IDW_TD_ETL_CTL_V.ETLCDCDATES`
    WHERE
      JOBNAME LIKE 'HRA_CORE_%-EXPERIENCE-WORKDAY'
  ),
  UPDT_DTTM = (
    SELECT
      ExtractEndDttm
    FROM
      `gcp-project.IDW_TD_ETL_CTL_V.ETLCDCDATES`
    WHERE
      JOBNAME LIKE 'HRA_CORE_%-EXPERIENCE-WORKDAY'
  );