-- SCHEMA MIGRATION
CREATE SCHEMA IF NOT EXISTS `gcp-project.HRA_CORE_T`;
CREATE SCHEMA IF NOT EXISTS `gcp-project.HRA_CORE_V`;
CREATE SCHEMA IF NOT EXISTS `gcp-project.IDW_TD_ETL_CTL`;
CREATE SCHEMA IF NOT EXISTS `gcp-project.IDW_TD_ETL_CTL_V`;

CREATE TABLE IF NOT EXISTS `gcp-project.HRA_CORE_T.EXPERIENCE` (
  CANDIDATE_ID STRING NOT NULL OPTIONS(description="Candidate's unique identifier"),
  SRC_FILE_DTTM TIMESTAMP NOT NULL OPTIONS(description="Source file timestamp"),
  MOST_RCNT_IND STRING OPTIONS(description="Indicator for the most recent record"),
  CURR_IND STRING OPTIONS(description="Indicator for the current active record"),
  EFF_END_DTTM TIMESTAMP OPTIONS(description="Effective end timestamp for the record"),
  UPDT_PRCS_ID INT64 OPTIONS(description="Process ID of the last update"),
  UPDT_DTTM TIMESTAMP OPTIONS(description="Timestamp of the last update")
)
CLUSTER BY CANDIDATE_ID;

CREATE OR REPLACE VIEW `gcp-project.HRA_CORE_V.EXPERIENCE` AS
SELECT * FROM `gcp-project.HRA_CORE_T.EXPERIENCE`;

CREATE TABLE IF NOT EXISTS `gcp-project.IDW_TD_ETL_CTL.ETLCDCDATES` (
  ProcessID INT64 NOT NULL,
  ExtractEndDttm TIMESTAMP,
  JOBNAME STRING
)
CLUSTER BY JOBNAME;

CREATE OR REPLACE VIEW `gcp-project.IDW_TD_ETL_CTL_V.ETLCDCDATES` AS
SELECT * FROM `gcp-project.IDW_TD_ETL_CTL.ETLCDCDATES`;

CREATE TABLE IF NOT EXISTS `gcp-project.HRA_CORE_T.ASSOCIATE_ADGROUP_SNAPSHOT` (
    SNAPSHOT_DT DATE NOT NULL,
    ASSOCIATE_ID STRING NOT NULL,
    AD_GROUP_NAME STRING NOT NULL,
    EXTRACT_DTTM TIMESTAMP
)
PARTITION BY SNAPSHOT_DT;

CREATE TABLE IF NOT EXISTS `gcp-project.HRA_CORE_T.HRA_PROC_ADGRP_MANUALUSERS` (
    USER_ID STRING NOT NULL,
    AD_GROUP_NAME STRING NOT NULL,
    ADDED_BY STRING,
    ADDED_DTTM TIMESTAMP
);