MERGE `gcp-s-dwa-db-250-span-pl.HRA_CORE_T.HRA_PROC_ADGRP_MANUALUSERS` AS T
USING `gcp-s-dwa-db-250-span-pl.HRA_STG.SRC_MANUAL_USERS` AS S
ON T.USER_ID = S.USER_ID AND T.AD_GROUP = S.AD_GROUP
WHEN NOT MATCHED THEN
  INSERT (USER_ID, AD_GROUP, ADDED_BY, ADDED_TIMESTAMP)
  VALUES (S.USER_ID, S.AD_GROUP, S.ADDED_BY, CURRENT_TIMESTAMP());