-- SCHEMA MIGRATION
CREATE SCHEMA IF NOT EXISTS HRA_STG_WORKDAY_V;
CREATE SCHEMA IF NOT EXISTS HRA_CORE_V;
CREATE SCHEMA IF NOT EXISTS HRA_CORE_T;

CREATE OR REPLACE VIEW HRA_STG_WORKDAY_V.STG_EMPLOYEE AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW HRA_STG_WORKDAY_V.STG_JOB_PROFILE AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW HRA_STG_WORKDAY_V.STG_OR_SUPERVISORY_ORGANIZATIONS AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW HRA_STG_WORKDAY_V.STG_EM_PERSONAL AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW HRA_CORE_V.HRA_PROC_ADGRP_MANUALUSERS AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW HRA_CORE_V.ASSOCIATE_ADGROUP_SNAPSHOT AS SELECT 'base_table_stub' AS stub;

CREATE TABLE IF NOT EXISTS HRA_CORE_T.ASSOCIATE_ADGROUP_ANOMALY_SNAPSHOT (
    ASSOC_USER_NAME STRING OPTIONS(description='Associate user name'),
    ASSOC_ADGROUP_ID STRING OPTIONS(description='Associate AD group ID'),
    EMPLOYEE_ID STRING OPTIONS(description='Employee ID'),
    LEGAL_FIRST_NAME STRING OPTIONS(description='Legal first name'),
    LEGAL_MIDDLE_NAME STRING OPTIONS(description='Legal middle name'),
    LEGAL_LAST_NAME STRING OPTIONS(description='Legal last name'),
    EMPLOYMENT_STATUS STRING OPTIONS(description='Employment status'),
    HIRE_DATE DATE OPTIONS(description='Hire date'),
    TERM_DATE DATE OPTIONS(description='Termination date'),
    FUNCTIONAL_GROUP_NAME STRING OPTIONS(description='Functional group name'),
    JOB_TITLE STRING OPTIONS(description='Job title'),
    SNAPSHOT_DATE DATE OPTIONS(description='Snapshot date')
)
PARTITION BY SNAPSHOT_DATE;