
-- Converted BTEQ script to BigQuery SQL

-- VT_STG_EMPLOYEE
CREATE TEMP TABLE VT_STG_EMPLOYEE AS
SELECT *
FROM HRA_STG_WORKDAY_V.STG_EMPLOYEE
WHERE CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_EMPLOYEE);

-- VT_STG_ORG_HIERARCHY
CREATE TEMP TABLE VT_STG_ORG_HIERARCHY AS
SELECT SUPERVISORY_ORGANIZATION_ID, SUPERVISORY_ORGANIZATION_NAME, FUNCTIONAL_GROUP_CODE, BUSINESS_UNIT_NAME, FUNCTIONAL_GROUP_ID, FUNCTIONAL_GROUP_NAME
FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
WHERE CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY);

-- VT_STG_JOB_PROFILE
CREATE TEMP TABLE VT_STG_JOB_PROFILE AS
SELECT JOB_CODE, JOB_TITLE, JOB_FAMILY, EXECUTIVE_INDICATOR
FROM HRA_STG_WORKDAY_V.STG_JOB_PROFILE
WHERE Inactive = 'False'
AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT CAST(MAX(SOURCE_FILE_DTTM) AS DATE) FROM HRA_STG_WORKDAY_V.STG_JOB_PROFILE);

-- VT_ADGRP_NTID
CREATE TEMP TABLE VT_ADGRP_NTID (
    NTID STRING,
    ADGRP_ID STRING
);

-- HRA_ALLHR
INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_ALLHR',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.FUNCTIONAL_GROUP_CODE = 'Human Resources' OR ORG.FUNCTIONAL_GROUP_ID = '10001008' OR A.position_id IN ('50258926','50830553'))
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_PITEAM
CREATE TEMP TABLE VT_EMP_HRCY_Piteam AS
SELECT DISTINCT E.EMPLOYEE_ID, E.LEGAL_LAST_NAME, E.NTID, E.POSITION_ID, OH.LEVEL_01_MANAGER_POSITION_ID AS MANAGER_POSITION_ID, OH.LEVEL_02_MANAGER_POSITION_ID AS SRMANAGER_POSITION_ID
FROM VT_STG_EMPLOYEE AS E
JOIN HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY AS OH
    ON E.SUPERVISORY_ORGANIZATION_ID = OH.SUPERVISORY_ORGANIZATION_ID AND E.SUPERVISORY_ORGANIZATION_ID IN ('70002388','70002768')
WHERE CAST(OH.SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_PITEAM',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    ORG.SUPERVISORY_ORGANIZATION_ID IN ('70002388','70002768')
    AND A.EMPLOYEE_ID IN (SELECT DISTINCT EMPLOYEE_ID FROM VT_EMP_HRCY_Piteam)
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_PITEAM',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.POSITION_ID IN (
        SELECT DISTINCT MANAGER_POSITION_ID FROM VT_EMP_HRCY_Piteam
        UNION DISTINCT
        SELECT DISTINCT SRMANAGER_POSITION_ID FROM VT_EMP_HRCY_Piteam WHERE SRMANAGER_POSITION_ID <> '50541685'
    )
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_HRVP
INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_HRVP',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.FUNCTIONAL_GROUP_CODE = 'Human Resources' OR ORG.FUNCTIONAL_GROUP_id = '10001008')
    AND J.EXECUTIVE_INDICATOR IN ('Chief Officer','Senior Vice President','Vice President')
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_HRESP
INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_HRESP',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (A.TMO_HR_PARTNER_MANAGER_RBSG_C = 'YES' OR A.TMO_HR_PARTNER_ADDITIONAL_RBSG_C = 'YES' OR A.HR_PARTNER = 'Yes' OR A.NTID = 'NVitela1')
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_TATEAM
INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_TATEAM',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (A.TMO_RECRUITER_ADDITIONAL_C = 'YES' OR A.RECRUITER = 'Yes')
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- VT_TMP_ORG
CREATE TEMP TABLE VT_TMP_ORG AS
SELECT DISTINCT REFERENCE_ID, PARENT_REFERENCE_ID
FROM HRA_STG_WORKDAY_V.STG_OR_SUPERVISORY_ORGANIZATIONS
WHERE CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_OR_SUPERVISORY_ORGANIZATIONS);

-- HRA_HRPAI
CREATE TEMP TABLE VT_HRA_PAI_ORG AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl
    FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50395331'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50395331'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50395331'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

CREATE TEMP TABLE VT_HRA_PAI_ORG_AVOID AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl
    FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50516252', '50490998')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50516252', '50490998')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50516252', '50490998')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

CREATE TEMP TABLE VT_HRAPAI_POSITIONS AS
SELECT DISTINCT POSITION_ID
FROM VT_STG_EMPLOYEE
WHERE
    (SUPERVISORY_ORGANIZATION_ID IN (SELECT org_id FROM VT_HRA_PAI_ORG EXCEPT DISTINCT SELECT ORG_ID FROM VT_HRA_PAI_ORG_AVOID)
    AND POSITION_ID NOT IN ('50516252', '50490998'))
    OR POSITION_ID = '50395331';

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_HRPAI',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.POSITION_ID IN (SELECT POSITION_ID FROM VT_HRAPAI_POSITIONS)
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_SLT
INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_SLT',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    COALESCE(A.SLT_FLAG, 'NO') = 'YES'
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_VPPLUS
INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_VPPLUS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    J.EXECUTIVE_INDICATOR IN ('Chief Officer','Senior Vice President','Vice President')
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_COMMISSIONS
CREATE TEMP TABLE VT_HRA_COMMISSIONS_ORG AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN ('50182337', '70002308', '50155156', '50268382', '70002372', '70002315', '70010906', '70010494')
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN ('50182337', '70002308', '50155156', '50268382', '70002372', '70002315', '70010906', '70010494')
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN ('50182337', '70002308', '50155156', '50268382', '70002372', '70002315', '70010906', '70010494');

CREATE TEMP TABLE VT_L1_MANAGER_PSTN_ID_COMMISSIONS AS
SELECT LEVEL_01_MANAGER_POSITION_ID AS POSITION_ID
FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
WHERE SUPERVISORY_ORGANIZATION_ID IN ('50182337', '70002308', '50155156', '50268382', '70002372', '70002315', '70010906', '70010494')
AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_COMMISSIONS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT ORG_ID FROM VT_HRA_COMMISSIONS_ORG)
    OR A.POSITION_ID IN (SELECT POSITION_ID FROM VT_L1_MANAGER_PSTN_ID_COMMISSIONS))
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_DIRECTOR
INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_DIRECTOR',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    J.EXECUTIVE_INDICATOR IN ('Chief Officer','Director','Senior Director','Senior Vice President','Vice President')
    AND (ORG.FUNCTIONAL_GROUP_CODE = 'Human Resources' OR ORG.FUNCTIONAL_GROUP_ID = '10001008' OR A.position_id = '50258926')
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_EDIRECTORPLUS
INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_EDIRECTORPLUS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    J.EXECUTIVE_INDICATOR IN ('Chief Officer','Director','Senior Director','Senior Vice President','Vice President')
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_EXECASST
INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_EXECASST',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (TRIM(J.JOB_FAMILY) IN ('Executive Support','General Support') OR LTRIM(J.JOB_CODE, '0') IN ('750048','771726','771610') OR A.NTID = 'JGRIFFI11')
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_COMP
CREATE TEMP TABLE VT_CTE1 AS
SELECT DISTINCT EMPLOYEE_ID, MANAGER_ID
FROM HRA_STG_WORKDAY_V.STG_EM_PERSONAL
WHERE
    CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_EM_PERSONAL)
    AND TERMINATED = 'N'
    AND EMFUNCTION = '10001008'
    AND JOB_CODE IN (SELECT JOB_CODE FROM VT_STG_JOB_PROFILE WHERE job_family = 'Compensation');

CREATE TEMP TABLE VT_CTE2 AS
SELECT EM.EMPLOYEE_ID
FROM VT_CTE1
JOIN HRA_STG_WORKDAY_V.STG_EM_PERSONAL AS EM ON EM.MANAGER_ID = VT_CTE1.EMPLOYEE_ID
WHERE
    CAST(EM.SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_EM_PERSONAL)
    AND EM.TERMINATED = 'N';

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_COMP',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.EMPLOYEE_ID IN (
        SELECT EMPLOYEE_ID FROM VT_CTE1
        UNION DISTINCT
        SELECT EMPLOYEE_ID FROM VT_CTE2
        UNION DISTINCT
        SELECT MANAGER_ID FROM VT_CTE1
    )
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_BENEFITS
CREATE TEMP TABLE VT_HRA_BENEFITS_ORG AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50425380')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50425380')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50425380')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_BENEFITS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT org_id FROM vt_HRA_BENEFITS_ORG) OR A.position_id IN ('50425380','50626141'))
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_DITEAM
CREATE TEMP TABLE VT_HRA_DITEAM_ORG AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50309620'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50309620'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_DITEAM',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT org_id FROM VT_HRA_DITEAM_ORG) OR A.position_id = '50309620')
    AND A.position_id <> '50483174'
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_HROPS
CREATE TEMP TABLE VT_HRA_HROPS_ORG AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50824355'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50824355'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_HROPS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT org_id FROM VT_HRA_HROPS_ORG) OR A.POSITION_ID IN ('50824355'))
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_EMPLOYEECARE
INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_EMPLOYEECARE',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN ('50392277','50139173','70000121') OR A.POSITION_ID IN ('50517342'))
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_PAYROLL
CREATE TEMP TABLE VT_HRA_PAYROLL_ORG AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50473433'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50473433'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50473433'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

CREATE TEMP TABLE VT_HRA_PAYROLL_POSITIONS AS
SELECT DISTINCT POSITION_ID FROM VT_STG_EMPLOYEE
WHERE SUPERVISORY_ORGANIZATION_ID IN (SELECT org_id FROM VT_HRA_PAYROLL_ORG)
OR POSITION_ID IN ('50473433','50834813','50824355');

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_PAYROLL',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.POSITION_ID IN (SELECT POSITION_ID FROM VT_HRA_PAYROLL_POSITIONS)
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_PEOPLMGR
INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_PEOPLMGR',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.MANAGEMENT_CHAIN = 'YES'
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_HRSYSTEMS
INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_HRSYSTEMS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (A.SUPERVISORY_ORGANIZATION_ID IN (
        SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
        WHERE LEVEL_01_MANAGER_POSITION_ID = '50233087'
        AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
    ) OR A.POSITION_ID = '50233087')
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_CARE_LD
CREATE TEMP TABLE VT_HRA_CARE_LD_ORG AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50626194'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50626194'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50626194'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_CARE_LD',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT ORG_ID FROM VT_HRA_CARE_LD_ORG) OR A.position_id IN ('50626194'))
    AND A.JOB_ID IN (
        SELECT DISTINCT JOB_CODE
        FROM HRA_STG_WORKDAY_V.STG_JOB_PROFILE
        -- Ambiguity Note: VOLT.TMODECRYPT_HR is a proprietary Teradata function.
        -- The logic needs to be replicated in BigQuery. Assuming it decrypts FLSA_ENCR.
        WHERE Inactive = 'False' AND FLSA_ENCR = 'EXEMPT' -- Replace with actual decryption logic
        AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT CAST(MAX(SOURCE_FILE_DTTM) AS DATE) FROM HRA_STG_WORKDAY_V.STG_JOB_PROFILE)
    )
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_ELS_SUPPORT_TEAM
CREATE TEMP TABLE VT_HRA_ELS_SUPPORT_TEAM_ORG AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50560441'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50560441'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50560441'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_ELS_SUPPORT_TEAM',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT org_id FROM VT_HRA_ELS_SUPPORT_TEAM_ORG) OR A.POSITION_ID IN ('50560441'))
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_HRFIN
CREATE TEMP TABLE VT_HRA_HRFIN_ORG AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50170381'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50170381'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_HRFIN',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT org_id FROM VT_HRA_HRFIN_ORG) OR A.position_id IN ('50170381','50197140'))
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_LOATEAM
CREATE TEMP TABLE VT_HRA_LOATEAM AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50516252','50490998')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50516252','50490998')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50516252','50490998')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_LOATEAM',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT org_id FROM VT_HRA_LOATEAM) OR A.POSITION_ID IN ('50516252','50490998'))
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_IRISK
CREATE TEMP TABLE VT_HRA_IRISK AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50092627'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50092627'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50092627'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_IRISK',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT org_id FROM VT_HRA_IRISK) OR A.POSITION_ID = '50092627')
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_HRTALENT
CREATE TEMP TABLE VT_HRA_HRTALENT_ORG AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50830895')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50830895')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50830895')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_HRTALENT',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT ORG_ID FROM VT_HRA_HRTALENT_ORG) OR A.POSITION_ID = '50830895')
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_HRSEV
CREATE TEMP TABLE VT_HRA_HRSEV_ORG AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50428967')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50428967')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50428967')
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_HRSEV',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT ORG_ID FROM VT_HRA_HRSEV_ORG) OR A.POSITION_ID = '50428967')
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_CGSO
CREATE TEMP TABLE VT_HRA_CGSO_ORG AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50565676'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50565676'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50565676'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_CGSO',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT org_id FROM VT_HRA_CGSO_ORG) OR A.POSITION_ID = '50565676')
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_ResourcePlanning
CREATE TEMP TABLE VT_ResourcePlanning AS
SELECT EMPLOYEE_ID
FROM HRA_STG_WORKDAY_V.STG_EM_PERSONAL
WHERE
    EMFUNCTION = '10001005'
    AND AREA = '20001062'
    AND ACTIVE_STATUS = 'Y'
    AND JOB_TITLE NOT LIKE '%ADMINISTRATIVE%'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_EM_PERSONAL)
    AND MANAGER_ID IN (
        SELECT EMPLOYEE_ID
        FROM HRA_STG_WORKDAY_V.STG_EM_PERSONAL
        WHERE (POSITION_TITLE LIKE '%MANAGER, BUSINESS ANALYSIS%' OR POSITION_TITLE LIKE '%RESOURCE PLANNING%')
        AND ACTIVE_STATUS = 'Y'
        AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_EM_PERSONAL)
    );

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_ResourcePlanning',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM VT_ResourcePlanning)
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_HRSRPLUS
CREATE TEMP TABLE VT_HRA_HRSRPLUS AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50829146'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50829146'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50829146'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

CREATE TEMP TABLE VT_EMP_HRA_HRSRPLUS AS
SELECT DISTINCT A.EMPLOYEE_ID
FROM VT_STG_EMPLOYEE AS A
JOIN HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    CAST(ORG.SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
    AND (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (SELECT ORG_ID FROM VT_HRA_HRSRPLUS)
        OR (
            (ORG.FUNCTIONAL_GROUP_CODE= 'Human Resources' OR ORG.FUNCTIONAL_GROUP_id='10001008')
            AND J.EXECUTIVE_INDICATOR IN ('Director','Chief Officer','Vice President','Senior Director','Senior Vice President','Senior Director IC','Director IC')
        )
    )
UNION DISTINCT
SELECT DISTINCT A.EMPLOYEE_ID
FROM VT_STG_EMPLOYEE AS A
WHERE A.POSITION_ID IN (
    SELECT LEVEL_01_MANAGER_POSITION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE SUPERVISORY_ORGANIZATION_ID = '70010541'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_HRSRPLUS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM VT_EMP_HRA_HRSRPLUS)
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

-- HRA_RR
CREATE TEMP TABLE VT_HRA_RR AS
WITH RECURSIVE temp_table AS (
    SELECT REFERENCE_ID, PARENT_REFERENCE_ID, 0 AS lvl FROM VT_TMP_ORG
    UNION ALL
    SELECT indirect.REFERENCE_ID, direct.PARENT_REFERENCE_ID, direct.lvl + 1 AS new_lvl
    FROM VT_TMP_ORG AS indirect, temp_table AS direct
    WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50284084'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT PARENT_REFERENCE_ID AS ORG_ID FROM temp_table
WHERE PARENT_REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50284084'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
)
UNION DISTINCT
SELECT REFERENCE_ID AS ORG_ID FROM temp_table
WHERE REFERENCE_ID IN (
    SELECT DISTINCT SUPERVISORY_ORGANIZATION_ID
    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
    WHERE LEVEL_01_MANAGER_POSITION_ID = '50284084'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (SELECT MAX(CAST(SOURCE_FILE_DTTM AS DATE)) FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY)
);

CREATE TEMP TABLE VT_HRA_RR_POSITIONS AS
SELECT DISTINCT POSITION_ID
FROM VT_STG_EMPLOYEE
WHERE
    SUPERVISORY_ORGANIZATION_ID IN (SELECT org_id FROM VT_HRA_RR)
    OR POSITION_ID = '50284084';

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT
    'HRA_RR',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
JOIN
    VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
JOIN
    VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.POSITION_ID IN (SELECT POSITION_ID FROM VT_HRA_RR_POSITIONS)
    AND CASE A.EMPLOYMENT_STATUS WHEN 'Terminated' THEN 'R' WHEN 'Active' THEN 'A' ELSE 'R' END = 'A';

INSERT INTO VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT DISTINCT ADGRP_ID, NTID
FROM (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY NTID, ADGRP_ID ORDER BY LOAD_DTTM DESC) as rn
    FROM HRA_CORE_V.HRA_PROC_ADGRP_MANUALUSERS
) AS A
WHERE ACTION_IND = 'A' AND rn = 1;

-- Final Insert
CREATE OR REPLACE TABLE HRA_CORE_T.ASSOCIATE_ADGROUP_ANOMALY_SNAPSHOT AS
SELECT
    A.ASSOC_USER_NAME,
    A.ASSOC_ADGROUP_ID,
    B.EMPLOYEE_ID,
    B.LEGAL_FIRST_NAME,
    B.LEGAL_MIDDLE_NAME,
    B.LEGAL_LAST_NAME,
    B.EMPLOYMENT_STATUS,
    B.HIRE_DATE,
    CASE WHEN B.HIRE_DATE < B.TERMINATION_DATE THEN B.TERMINATION_DATE END AS TERM_DATE,
    ORG.FUNCTIONAL_GROUP_NAME,
    J.JOB_TITLE,
    CURRENT_DATE() AS SNAPSHOT_DATE
FROM (
    SELECT DISTINCT TRIM(ASSOC_USER_NAME) AS ASSOC_USER_NAME, TRIM(ASSOC_ADGROUP_ID) AS ASSOC_ADGROUP_ID
    FROM HRA_CORE_V.ASSOCIATE_ADGROUP_SNAPSHOT
    EXCEPT DISTINCT
    SELECT DISTINCT TRIM(NTID) AS ASSOC_USER_NAME, TRIM(ADGRP_ID) AS ASSOC_ADGROUP_ID
    FROM VT_ADGRP_NTID
) AS A
LEFT JOIN (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY NTID ORDER BY SOURCE_FILE_DTTM DESC) as rn
    FROM HRA_STG_WORKDAY_V.STG_EMPLOYEE
) AS B ON A.ASSOC_USER_NAME = B.NTID AND B.rn = 1
LEFT JOIN VT_STG_ORG_HIERARCHY AS ORG ON B.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
LEFT JOIN VT_STG_JOB_PROFILE AS J ON B.JOB_ID = J.JOB_CODE;