"""
Configuration module for CRM data ingestion pipelines.

This module defines the specifications for each data entity to be processed,
based on the Technical Requirement Document (TRD). Each configuration object
details the source, target, schema, primary key, and optimization strategies
for a BigQuery table.
"""

TABLE_CONFIGURATIONS = [
    {
        "id": "TR-CUST-001",
        "source_dataset": "Raw",
        "source_table": "stg_customer",
        "target_dataset": "Curated",
        "target_table": "customer",
        "primary_key": "customer_id",
        "watermark_column": "created_on",
        "columns": [
            ("customer_id", "STRING"),
            ("customer_type", "STRING"),
            ("name", "STRING"),
            ("company_name", "STRING"),
            ("industry", "STRING"),
            ("email", "STRING"),
            ("phone", "STRING"),
            ("website", "STRING"),
            ("address_line1", "STRING"),
            ("address_line2", "STRING"),
            ("city", "STRING"),
            ("state", "STRING"),
            ("country", "STRING"),
            ("postal_code", "STRING"),
            ("created_on", "TIMESTAMP"),
            ("modified_on", "TIMESTAMP"),
            ("is_active", "BOOL"),
        ],
        "partition": None,
        "cluster_by": ["customer_type", "industry"],
    },
    {
        "id": "TR-LEAD-001",
        "source_dataset": "Raw",
        "source_table": "stg_lead",
        "target_dataset": "Curated",
        "target_table": "lead",
        "primary_key": "lead_id",
        "watermark_column": "created_on",
        "columns": [
            ("lead_id", "STRING"),
            ("topic", "STRING"),
            ("first_name", "STRING"),
            ("last_name", "STRING"),
            ("company_name", "STRING"),
            ("email", "STRING"),
            ("phone", "STRING"),
            ("lead_source", "STRING"),
            ("status", "STRING"),
            ("customer_id", "STRING"),
            ("created_on", "TIMESTAMP"),
            ("qualified_on", "TIMESTAMP"),
            ("owner_id", "STRING"),
        ],
        "partition": {"field": "created_on", "type": "DATE"},
        "cluster_by": ["lead_source", "status"],
    },
    {
        "id": "TR-OPP-001",
        "source_dataset": "Raw",
        "source_table": "stg_opportunity",
        "target_dataset": "Curated",
        "target_table": "opportunity",
        "primary_key": "opportunity_id",
        "watermark_column": "created_on",
        "columns": [
            ("opportunity_id", "STRING"),
            ("name", "STRING"),
            ("customer_id", "STRING"),
            ("originating_lead_id", "STRING"),
            ("stage", "STRING"),
            ("status", "STRING"),
            ("estimated_value", "FLOAT64"),
            ("probability", "FLOAT64"),
            ("close_date", "DATE"),
            ("created_on", "TIMESTAMP"),
            ("owner_id", "STRING"),
        ],
        "partition": {"field": "created_on", "type": "DATE"},
        "cluster_by": ["stage", "status"],
    },
    {
        "id": "TR-QUOTE-001",
        "source_dataset": "Raw",
        "source_table": "stg_quote",
        "target_dataset": "Curated",
        "target_table": "quote",
        "primary_key": "quote_id",
        "watermark_column": "created_on",
        "columns": [
            ("quote_id", "STRING"),
            ("quote_number", "STRING"),
            ("opportunity_id", "STRING"),
            ("customer_id", "STRING"),
            ("status", "STRING"),
            ("total_amount", "FLOAT64"),
            ("currency", "STRING"),
            ("valid_from", "DATE"),
            ("valid_to", "DATE"),
            ("created_on", "TIMESTAMP"),
        ],
        "partition": {"field": "created_on", "type": "DATE"},
        "cluster_by": ["status"],
    },
    {
        "id": "TR-QTDL-001",
        "source_dataset": "Raw",
        "source_table": "stg_quote_detail",
        "target_dataset": "Curated",
        "target_table": "quote_detail",
        "primary_key": "quote_detail_id",
        "watermark_column": None,
        "columns": [
            ("quote_detail_id", "STRING"),
            ("quote_id", "STRING"),
            ("product_name", "STRING"),
            ("product_category", "STRING"),
            ("quantity", "INT64"),
            ("unit_price", "FLOAT64"),
            ("discount", "FLOAT64"),
            ("total_amount", "FLOAT64"),
        ],
        "partition": None,
        "cluster_by": None,
    },
]
