-- HRA_CORE_T-ASSOCIATE_ADGROUP_SNAPSHOT--HRA_CORE_T-ASSOCIATE_ADGROUP_ANOMALY_SNAPSHOT.bteq

-- Generated by Gemini

/* Get the list of the active employees whose Position_ID or Job_ID or Supervisory_ID changed  */

CREATE TEMP TABLE VT_STG_EMPLOYEE AS
SELECT *
FROM
    `gcp-project.HRA_STG_WORKDAY_V.STG_EMPLOYEE`
WHERE
    CAST(SOURCE_FILE_DTTM AS DATE) = (
        SELECT
            MAX(CAST(SOURCE_FILE_DTTM AS DATE))
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_EMPLOYEE`
    );

CREATE TEMP TABLE VT_STG_ORG_HIERARCHY AS
SELECT
    SUPERVISORY_ORGANIZATION_ID,
    SUPERVISORY_ORGANIZATION_NAME,
    FUNCTIONAL_GROUP_CODE,
    BUSINESS_UNIT_NAME,
    FUNCTIONAL_GROUP_ID,
    FUNCTIONAL_GROUP_NAME
FROM
    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
WHERE
    CAST(SOURCE_FILE_DTTM AS DATE) = (
        SELECT
            MAX(CAST(SOURCE_FILE_DTTM AS DATE))
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
    );

CREATE TEMP TABLE VT_STG_JOB_PROFILE AS
SELECT
    JOB_CODE,
    JOB_TITLE,
    JOB_FAMILY,
    EXECUTIVE_INDICATOR
FROM
    `gcp-project.HRA_STG_WORKDAY_V.STG_JOB_PROFILE`
WHERE
    Inactive = 'False'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (
        SELECT
            CAST(MAX(SOURCE_FILE_DTTM) AS DATE)
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_JOB_PROFILE`
    );

CREATE TEMP TABLE VT_ADGRP_NTID (
    NTID STRING,
    ADGRP_ID STRING
);

/*AD GROUP - HRA_ALLHR*/
/*All employees in Human Resources (required for TA Dashboard)*/
INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_ALLHR',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.FUNCTIONAL_GROUP_CODE = 'Human Resources'
        OR ORG.FUNCTIONAL_GROUP_ID = '10001008'
        OR A.position_id IN ('50258926', '50830553')
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*AD GROUP - HRA_PITEAM*/
/*All employees in the People Insights team*/
/*supervisory org number
(Debi and Greg including managers and manager's manager (Rache) of the org)
Members of Supervisory Org X Debbi (70002388),
Manager of Supervisory Org X,
Manager's Manager of Supervisory Org X ,
Members of Supervisory Org Y Greg (70002768),
Manager of Supervisory Org Y,
Manager's Manager of Supervisory Org Y
Exclude Nathan Bushey*/
CREATE TEMP TABLE VT_EMP_HRCY_Piteam AS
SELECT
    DISTINCT E.EMPLOYEE_ID,
    E.LEGAL_LAST_NAME,
    E.NTID,
    E.POSITION_ID,
    OH.LEVEL_01_MANAGER_POSITION_ID AS MANAGER_POSITION_ID,
    OH.LEVEL_02_MANAGER_POSITION_ID AS SRMANAGER_POSITION_ID
FROM
    VT_STG_EMPLOYEE AS E
    INNER JOIN `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY` AS OH ON E.SUPERVISORY_ORGANIZATION_ID = OH.SUPERVISORY_ORGANIZATION_ID
    AND E.SUPERVISORY_ORGANIZATION_ID IN ('70002388', '70002768')
WHERE
    CAST(OH.SOURCE_FILE_DTTM AS DATE) = (
        SELECT
            MAX(CAST(SOURCE_FILE_DTTM AS DATE))
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_PITEAM',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    ORG.SUPERVISORY_ORGANIZATION_ID IN ('70002388', '70002768')
    AND A.EMPLOYEE_ID IN (
        SELECT
            DISTINCT EMPLOYEE_ID
        FROM
            VT_EMP_HRCY_Piteam
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_PITEAM',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.POSITION_ID IN (
        SELECT
            DISTINCT MANAGER_POSITION_ID AS POSITION_ID
        FROM
            VT_EMP_HRCY_Piteam
        UNION
        SELECT
            DISTINCT SRMANAGER_POSITION_ID AS POSITION_ID
        FROM
            VT_EMP_HRCY_Piteam
        WHERE
            SRMANAGER_POSITION_ID <> '50541685'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*AD Group - HRA_HRVP*/
/*HR VPs and Above*/
/*Functional Group = Human Resources and
Executive Indicator in
(Senior Vice President, Vice President, Chief Officer) or
[Job Code = 00750037 <- Job code not reliable]*/
INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_HRVP',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.FUNCTIONAL_GROUP_CODE = 'Human Resources'
        OR ORG.FUNCTIONAL_GROUP_id = '10001008'
    )
    AND J.EXECUTIVE_INDICATOR IN (
        'Chief Officer',
        'Senior Vice President',
        'Vice President'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*AD Group - HRA_HRESP*/
/*All HR Employees Success Partners at all levels (ESP population)
workday security role:
TMO_HR_PARTNER_MANAGER_RBSG_C
TMO_HR_PARTNER_ADDITIONAL_RBSG_C
HR_PARTNER (not on Employee source file)*/
INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_HRESP',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        A.TMO_HR_PARTNER_MANAGER_RBSG_C = 'YES'
        OR A.TMO_HR_PARTNER_ADDITIONAL_RBSG_C = 'YES'
        OR A.HR_PARTNER = 'Yes'
        OR A.NTID = 'NVitela1'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*AD Group - HRA_TAteam*/
/*All employees in Talent Acquisition*/
/*this is best served by the workday security role: RECRUITER, TMO_RECRUITER_ADDITIONAL_C*/
INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_TATEAM',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        A.TMO_RECRUITER_ADDITIONAL_C = 'YES'
        OR A.RECRUITER = 'Yes'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

CREATE TEMP TABLE VT_TMP_ORG AS
SELECT
    DISTINCT REFERENCE_ID,
    PARENT_REFERENCE_ID
FROM
    `gcp-project.HRA_STG_WORKDAY_V.STG_OR_SUPERVISORY_ORGANIZATIONS` AS org
WHERE
    DATE(org.SOURCE_FILE_DTTM) = (
        SELECT
            DATE(MAX(SOURCE_FILE_DTTM))
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_OR_SUPERVISORY_ORGANIZATIONS`
    );

/*AD Group - HRA_HRPAI
this includes all under Patrice position_id = 50395331 and including position_id = 50395331
should not include Joanna Makuannen and Dianne Arpin orgs and POSITION_ID IN (50516252, 50490998)
*/
/*  get all orgs under Patrice position_id = 50395331 */
CREATE TEMP TABLE VT_HRA_PAI_ORG AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50395331'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50395331'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50395331'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

/*  get all orgs under Joanna Makuannen and Dianne Arpin orgs and POSITION_ID IN (50516252, 50490998) this orgs should be avoided */
CREATE TEMP TABLE VT_HRA_PAI_ORG_AVOID AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50516252', '50490998')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50516252', '50490998')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50516252', '50490998')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

/* getting all position id's including 50395331 excluding (50516252, 50490998)*/
CREATE TEMP TABLE VT_HRAPAI_POSITIONS AS
SELECT
    DISTINCT POSITION_ID
FROM
    VT_STG_EMPLOYEE
WHERE
    (
        SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                org_id
            FROM
                VT_HRA_PAI_ORG
            WHERE
                ORG_ID NOT IN (
                    SELECT
                        ORG_ID
                    FROM
                        VT_HRA_PAI_ORG_AVOID
                )
        )
        AND POSITION_ID NOT IN ('50516252', '50490998')
    )
    OR POSITION_ID = '50395331';

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_HRPAI',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.POSITION_ID IN (
        SELECT
            POSITION_ID
        FROM
            VT_HRAPAI_POSITIONS
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/* HRA_SLT*/
INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_SLT',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    COALESCE(A.SLT_FLAG, 'NO') = 'YES'
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/* HRA_VPPLUS*/
INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_VPPLUS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    J.EXECUTIVE_INDICATOR IN (
        'Chief Officer',
        'Senior Vice President',
        'Vice President'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*AD Group - HRA_COMMISSIONS*/
CREATE TEMP TABLE VT_HRA_COMMISSIONS_ORG AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
) --- Child orgs
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        '50182337',
        '70002308',
        '50155156',
        '50268382',
        '70002372',
        '70002315',
        '70010906',
        '70010494'
    )
UNION
---original parent orgs as per req
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        '50182337',
        '70002308',
        '50155156',
        '50268382',
        '70002372',
        '70002315',
        '70010906',
        '70010494'
    )
UNION
---Original orgs as per req which is not part of parent orgs form above sql
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        '50182337',
        '70002308',
        '50155156',
        '50268382',
        '70002372',
        '70002315',
        '70010906',
        '70010494'
    );

---Position id of managers who is managing the required parent orgs
CREATE TEMP TABLE VT_L1_MANAGER_PSTN_ID_COMMISSIONS AS
SELECT
    LEVEL_01_MANAGER_POSITION_ID AS POSITION_ID
FROM
    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
WHERE
    SUPERVISORY_ORGANIZATION_ID IN (
        '50182337',
        '70002308',
        '50155156',
        '50268382',
        '70002372',
        '70002315',
        '70010906',
        '70010494'
    )
    AND DATE(SOURCE_FILE_DTTM) = (
        SELECT
            MAX(DATE(SOURCE_FILE_DTTM))
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_COMMISSIONS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                ORG_ID
            FROM
                VT_HRA_COMMISSIONS_ORG
        )
        OR A.POSITION_ID IN (
            SELECT
                POSITION_ID
            FROM
                VT_L1_MANAGER_PSTN_ID_COMMISSIONS
        )
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*AD Group - HRA_DIRECTOR*/
/*Employees that are
  directors, sr. directors, VP,
  Sr. VP, Exec. VP, CEO*/
INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT --P.PROCESS_ID,
    'HRA_DIRECTOR',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    J.EXECUTIVE_INDICATOR IN (
        'Chief Officer',
        'Director',
        'Senior Director',
        'Senior Vice President',
        'Vice President'
    )
    AND (
        ORG.FUNCTIONAL_GROUP_CODE = 'Human Resources'
        OR ORG.FUNCTIONAL_GROUP_ID = '10001008'
        OR A.position_id = '50258926'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*AD Group - HRA_EDIRECTORPLUS*/
/*Employees that are
  directors, sr. directors, VP,
  Sr. VP, Exec. VP, Derek Potter Position ID 50258926, CEO*/
INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_EDIRECTORPLUS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    J.EXECUTIVE_INDICATOR IN (
        'Chief Officer',
        'Director',
        'Senior Director',
        'Senior Vice President',
        'Vice President'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*AD Group - HRA_EXECASST*/
/*Executive Assistants
Employees with the business title of Assistant,
Executive or Assistant,
Executive to EVP or Sr. Assistant, Executive:
Job Family Name = Executive Support and
Job profile = Active
List of Job profiles:
Assistant, Executive; Assistant, Executive to COO;
Assistant, Executive to EVP; Sr Assistant, Executive;
Sr Manager, Office of the CEO*/
INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_EXECASST',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        TRIM(J.JOB_FAMILY) IN ('Executive Support', 'General Support')
        OR TRIM(LEADING '0' FROM J.JOB_CODE) IN ('750048', '771726', '771610')
        OR A.NTID = 'JGRIFFI11'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*AD GROUP - HRA_COMP*/
CREATE TEMP TABLE VT_CTE1 AS
SELECT
    DISTINCT EMPLOYEE_ID,
    MANAGER_ID
FROM
    `gcp-project.HRA_STG_WORKDAY_V.STG_EM_PERSONAL`
WHERE
    CAST(SOURCE_FILE_DTTM AS DATE) = (
        SELECT
            MAX(CAST(SOURCE_FILE_DTTM AS DATE))
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_EM_PERSONAL`
    )
    AND TERMINATED = 'N'
    AND EMFUNCTION = '10001008'
    AND JOB_CODE IN (
        SELECT
            JOB_CODE
        FROM
            VT_STG_JOB_PROFILE
        WHERE
            job_family = 'Compensation'
    );

CREATE TEMP TABLE VT_CTE2 AS
SELECT
    EM.EMPLOYEE_ID
FROM
    VT_CTE1
    INNER JOIN `gcp-project.HRA_STG_WORKDAY_V.STG_EM_PERSONAL` AS EM ON EM.MANAGER_ID = VT_CTE1.EMPLOYEE_ID
WHERE
    CAST(SOURCE_FILE_DTTM AS DATE) = (
        SELECT
            MAX(CAST(SOURCE_FILE_DTTM AS DATE))
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_EM_PERSONAL`
    )
    AND TERMINATED = 'N';

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_COMP',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.EMPLOYEE_ID IN (
        SELECT
            EMPLOYEE_ID
        FROM
            VT_CTE1
        UNION
        SELECT
            EMPLOYEE_ID
        FROM
            VT_CTE2
        UNION
        SELECT
            MANAGER_ID
        FROM
            VT_CTE1
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*HRA_BENEFITS FOR TMO FTES*/
/* LEVEL_01_MANAGER_POSITION_ID IN ('50425380','50626141') AND ORGS THAT ARE MAINTAINED BY LEVEL_01_MANAGER_POSITION_ID=('50425380')*/
CREATE TEMP TABLE VT_HRA_BENEFITS_ORG AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50425380')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50425380')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50425380')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_BENEFITS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                org_id
            FROM
                vt_HRA_BENEFITS_ORG
        )
        OR A.position_id IN ('50425380', '50626141')
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*HRA_DITEAM FOR TMO FTES*/
/* LEVEL_01_MANAGER_POSITION_ID='50309620' AND ORGS THAT ARE MAINTAINED BY LEVEL_01_MANAGER_POSITION_ID='50309620'*/
CREATE TEMP TABLE VT_HRA_DITEAM_ORG AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50309620'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50309620'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_DITEAM',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                org_id
            FROM
                VT_HRA_DITEAM_ORG
        )
        OR A.position_id = '50309620'
    )
    AND A.position_id <> '50483174'
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*HRA_HROPS addition*/
CREATE TEMP TABLE VT_HRA_HROPS_ORG AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50824355'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50824355'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_HROPS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                org_id
            FROM
                VT_HRA_HROPS_ORG
        )
        OR A.POSITION_ID IN ('50824355')
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*HRA_EMPLOYEECARE addition*/
INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_EMPLOYEECARE',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN ('50392277', '50139173', '70000121')
        OR A.POSITION_ID IN ('50517342')
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*HRA_PAYROLL base on EMPLOYEE_MANAGER_ID IN ('12541934', '211346') */
/* should be using ICSH view to include cross reporting between tmo and sprint*/
/*
CREATE MULTISET VOLATILE TABLE VT_HRA_PAYROLL_ORG
AS
(
WITH RECURSIVE temp_table (REFERENCE_ID,PARENT_REFERENCE_ID,lvl) AS
(
SEL REFERENCE_ID,PARENT_REFERENCE_ID , 0 AS lvl
FROM VT_TMP_ORG org

UNION ALL

SEL indirect.REFERENCE_ID,direct.PARENT_REFERENCE_ID , direct.lvl+1 AS new_lvl
FROM VT_TMP_ORG indirect, temp_table direct
WHERE direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT REFERENCE_ID AS ORG_ID
FROM temp_table
WHERE PARENT_REFERENCE_ID IN (SEL DISTINCT SUPERVISORY_ORGANIZATION_ID
                                    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
                            WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50824355','50328339')
                            AND  SOURCE_FILE_DTTM(DATE) =(SEL Max(SOURCE_FILE_DTTM)(DATE)
                                                            FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
                                                            )
                            )

UNION

SELECT PARENT_REFERENCE_ID AS ORG_ID
FROM temp_table
WHERE PARENT_REFERENCE_ID IN (SEL DISTINCT SUPERVISORY_ORGANIZATION_ID
                                    FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
                                WHERE LEVEL_01_MANAGER_POSITION_ID IN ('50824355','50328339')
                              AND  SOURCE_FILE_DTTM(DATE) =(SEL Max(SOURCE_FILE_DTTM)(DATE)
                                                                FROM HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY
                                                            )
                            )
)WITH DATA
PRIMARY INDEX(ORG_ID)
ON COMMIT PRESERVE ROWS;


INSERT INTO VT_ADGRP_NTID  (ADGRP_ID, NTID)
SEL DISTINCT
'HRA_PAYROLL',

A.NTID
FROM --HRA_CORE_T.HRA_PROC_CTRL_WRK P,
VT_STG_EMPLOYEE A,
VT_STG_ORG_HIERARCHY ORG,
VT_STG_JOB_PROFILE J
WHERE A.JOB_ID = J.JOB_CODE
AND A.SUPERVISORY_ORGANIZATION_ID =ORG.SUPERVISORY_ORGANIZATION_ID
AND( ORG.SUPERVISORY_ORGANIZATION_ID IN (SEL org_id FROM VT_HRA_PAYROLL_ORG)
OR  A.position_id IN ('50824355','50328339')
OR A.JOB_ID IN ('00751087','00758401','00758402','00760051','00770080','00770081','00770961','00771590','00771722','00773229','00773238','00773258','00771897','00773359','00771794')
)
AND CASE A.EMPLOYMENT_STATUS      WHEN 'Terminated' THEN 'R'     WHEN 'Active' THEN 'A'  ELSE 'R' END = 'A'
;
*/
--VT_HRA_PAYROLL
/*
Everyone rolling upto Steven Elliott(direct and indirect reportees) Steven Elliott (Psoition_ID 50473433) to be part of the AD Group.
*/
CREATE TEMP TABLE VT_HRA_PAYROLL_ORG AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50473433'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50473433'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50473433'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

--Fetch all the position ID's VT_HRA_PAYROLL_POSITIONS, with SElliot2(50473433),SDrisco1(50834813),MFrohoc1(50824355)
CREATE TEMP TABLE VT_HRA_PAYROLL_POSITIONS AS
SELECT
    DISTINCT POSITION_ID
FROM
    VT_STG_EMPLOYEE
WHERE
    SUPERVISORY_ORGANIZATION_ID IN (
        SELECT
            org_id
        FROM
            VT_HRA_PAYROLL_ORG
    )
    OR POSITION_ID IN ('50473433', '50834813', '50824355');

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_PAYROLL',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.POSITION_ID IN (
        SELECT
            POSITION_ID
        FROM
            VT_HRA_PAYROLL_POSITIONS
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/* ADGroup ---HRA_PEOPLMGR*/
/* All employees 9People managers)  with Management Chain Yes  */
INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_PEOPLMGR',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.MANAGEMENT_CHAIN = 'YES'
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

--------------HRA_HRSYSTEMS
INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_HRSYSTEMS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        A.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                DISTINCT SUPERVISORY_ORGANIZATION_ID
            FROM
                `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            WHERE
                LEVEL_01_MANAGER_POSITION_ID = '50233087'
                AND DATE(SOURCE_FILE_DTTM) = (
                    SELECT
                        MAX(DATE(SOURCE_FILE_DTTM))
                    FROM
                        `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
                )
        )
        OR A.POSITION_ID = '50233087'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

--------------HRA_CARE_LD
CREATE TEMP TABLE VT_HRA_CARE_LD_ORG AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50626194'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50626194'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50626194'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_CARE_LD',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                ORG_ID
            FROM
                VT_HRA_CARE_LD_ORG
        )
        OR A.position_id IN ('50626194')
    )
    AND A.JOB_ID IN (
        SELECT
            DISTINCT JOB_CODE
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_JOB_PROFILE`
        WHERE
            Inactive = 'False'
            AND VOLT.TMODECRYPT_HR(FLSA_ENCR, 'FLSA') = 'EXEMPT'
            AND CAST(SOURCE_FILE_DTTM AS DATE) = (
                SELECT
                    CAST(MAX(SOURCE_FILE_DTTM) AS DATE)
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_JOB_PROFILE`
            )
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

--------------HRA_ELS_SUPPORT_TEAM
CREATE TEMP TABLE VT_HRA_ELS_SUPPORT_TEAM_ORG AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50560441'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50560441'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50560441'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_ELS_SUPPORT_TEAM',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                org_id
            FROM
                VT_HRA_ELS_SUPPORT_TEAM_ORG
        )
        OR A.POSITION_ID IN ('50560441')
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*HRA_HRFIN FOR TMO FTES*/
/* LEVEL_01_MANAGER_POSITION_ID='50170381' AND ORGS THAT ARE MAINTAINED BY LEVEL_01_MANAGER_POSITION_ID='50170381'*/
CREATE TEMP TABLE VT_HRA_HRFIN_ORG AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50170381'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50170381'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_HRFIN',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                org_id
            FROM
                VT_HRA_HRFIN_ORG
        )
        OR A.position_id IN ('50170381', '50197140')
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

CREATE TEMP TABLE VT_HRA_LOATEAM AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50516252', '50490998')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50516252', '50490998')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50516252', '50490998')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_LOATEAM',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                org_id
            FROM
                VT_HRA_LOATEAM
        )
        OR A.POSITION_ID IN ('50516252', '50490998')
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*  HRA_IRISK  */
CREATE TEMP TABLE VT_HRA_IRISK AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50092627'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50092627'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50092627'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_IRISK',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                org_id
            FROM
                VT_HRA_IRISK
        )
        OR A.POSITION_ID = '50092627'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*AD GROUP - HRA_HRTALENT*/
CREATE TEMP TABLE VT_HRA_HRTALENT_ORG AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50830895')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50830895')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50830895')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_HRTALENT',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                ORG_ID
            FROM
                VT_HRA_HRTALENT_ORG
        )
        OR A.POSITION_ID = '50830895'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/*AD Group - HRA_HRSEV
 Severance
Org ID 50428967 + Org Manager*/
CREATE TEMP TABLE VT_HRA_HRSEV_ORG AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50428967')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50428967')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID IN ('50428967')
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_HRSEV',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                ORG_ID
            FROM
                VT_HRA_HRSEV_ORG
        )
        OR A.POSITION_ID = '50428967'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

/* HRA_CGSO  Employees rolling up to meghan weed position id 50565676 and including meghan weed*/
CREATE TEMP TABLE VT_HRA_CGSO_ORG AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50565676'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50565676'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50565676'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_CGSO',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                org_id
            FROM
                VT_HRA_CGSO_ORG
        )
        OR A.POSITION_ID = '50565676'
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

----------HRA_ResourcePlanning --------------------
/*
Active employees with customorg_functionalgroup_id='10001005' ---Customer Experience
customorg_area = '20001062' ---Planning and Strategy
job_title shouldn't be adminstrative
Manager position title should contain %MANAGER, BUSINESS ANALYSIS%  or %RESOURCE PLANNING%
*/
CREATE TEMP TABLE VT_ResourcePlanning AS
SELECT
    EMPLOYEE_ID
FROM
    `gcp-project.HRA_STG_WORKDAY_V.STG_EM_PERSONAL`
WHERE
    EMFUNCTION = '10001005'
    AND AREA = '20001062'
    AND ACTIVE_STATUS = 'Y'
    AND JOB_TITLE NOT LIKE '%ADMINISTRATIVE%'
    AND CAST(SOURCE_FILE_DTTM AS DATE) = (
        SELECT
            MAX(CAST(SOURCE_FILE_DTTM AS DATE))
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_EM_PERSONAL`
    )
    AND MANAGER_ID IN (
        SELECT
            EMPLOYEE_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_EM_PERSONAL`
        WHERE
            (
                POSITION_TITLE LIKE '%MANAGER, BUSINESS ANALYSIS%'
                OR POSITION_TITLE LIKE '%RESOURCE PLANNING%'
            )
            AND ACTIVE_STATUS = 'Y'
            AND CAST(SOURCE_FILE_DTTM AS DATE) = (
                SELECT
                    MAX(CAST(SOURCE_FILE_DTTM AS DATE))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_EM_PERSONAL`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_ResourcePlanning',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.EMPLOYEE_ID IN (
        SELECT
            EMPLOYEE_ID
        FROM
            VT_ResourcePlanning
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

----------AD GROUP - HRA_HRSRPLUS--------------------
/*
employees who is rolling up to Heddy Gagne, POSITION_ID = 50829146
OR
Functional group ‘Human Resources’ and executive indicator should be director or above
(Plus)
Whoever is managing organization 'Human Resources', adding that person to ADGroup 'HRA_HRSRPLUS'
*/
CREATE TEMP TABLE VT_HRA_HRSRPLUS AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50829146'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50829146'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50829146'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

--VT_EMP_HRA_HRSRPLUS
CREATE TEMP TABLE VT_EMP_HRA_HRSRPLUS AS
SELECT
    DISTINCT A.EMPLOYEE_ID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY` AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    CAST(ORG.SOURCE_FILE_DTTM AS DATE) = (
        SELECT
            MAX(CAST(SOURCE_FILE_DTTM AS DATE))
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
    )
    AND (
        ORG.SUPERVISORY_ORGANIZATION_ID IN (
            SELECT
                ORG_ID
            FROM
                VT_HRA_HRSRPLUS
        ) ---- employees who is rolling up to Heddy Gagne
        OR (
            (
                ORG.FUNCTIONAL_GROUP_CODE = 'Human Resources'
                OR ORG.FUNCTIONAL_GROUP_id = '10001008'
            )
            AND J.EXECUTIVE_INDICATOR IN (
                'Director',
                'Chief Officer',
                'Vice President',
                'Senior Director',
                'Senior Vice President',
                'Senior Director IC',
                'Director IC'
            )
        ) -- functional group 'Human Resources' and executive indicator should be director or above
    )
UNION
----- Whoever is managing organization 'Human Resources', adding that person to ADGroup 'HRA_HRSRPLUS'
SELECT
    DISTINCT A.EMPLOYEE_ID
FROM
    VT_STG_EMPLOYEE AS A
WHERE
    A.POSITION_ID IN (
        SELECT
            LEVEL_01_MANAGER_POSITION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            SUPERVISORY_ORGANIZATION_ID = '70010541'
            AND CAST(SOURCE_FILE_DTTM AS DATE) = (
                SELECT
                    MAX(CAST(SOURCE_FILE_DTTM AS DATE))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_HRSRPLUS',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.EMPLOYEE_ID IN (
        SELECT
            EMPLOYEE_ID
        FROM
            VT_EMP_HRA_HRSRPLUS
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

--VT_HRA_RR
/*
Everyone rolling upto Michelle Lizak(direct and indirect reportees) and Michelle Lizak (Psoition_ID 50284084) to be part of the AD Group.
*/
CREATE TEMP TABLE VT_HRA_RR AS WITH temp_table AS (
    SELECT
        REFERENCE_ID,
        PARENT_REFERENCE_ID,
        0 AS lvl
    FROM
        VT_TMP_ORG AS org
    UNION ALL
    SELECT
        indirect.REFERENCE_ID,
        direct.PARENT_REFERENCE_ID,
        direct.lvl + 1 AS new_lvl
    FROM
        VT_TMP_ORG AS indirect,
        temp_table AS direct
    WHERE
        direct.REFERENCE_ID = indirect.PARENT_REFERENCE_ID
)
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50284084'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    PARENT_REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    PARENT_REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50284084'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    )
UNION
SELECT
    REFERENCE_ID AS ORG_ID
FROM
    temp_table
WHERE
    REFERENCE_ID IN (
        SELECT
            DISTINCT SUPERVISORY_ORGANIZATION_ID
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
        WHERE
            LEVEL_01_MANAGER_POSITION_ID = '50284084'
            AND DATE(SOURCE_FILE_DTTM) = (
                SELECT
                    MAX(DATE(SOURCE_FILE_DTTM))
                FROM
                    `gcp-project.HRA_STG_WORKDAY_V.STG_ORG_HIERARCHY`
            )
    );

--Fetch all the position ID's VT_HRA_RR_POSITIONS
CREATE TEMP TABLE VT_HRA_RR_POSITIONS AS
SELECT
    DISTINCT POSITION_ID
FROM
    VT_STG_EMPLOYEE
WHERE
    SUPERVISORY_ORGANIZATION_ID IN (
        SELECT
            org_id
        FROM
            VT_HRA_RR
    )
    OR POSITION_ID = '50284084';

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT 'HRA_RR',
    A.NTID
FROM
    VT_STG_EMPLOYEE AS A
    INNER JOIN VT_STG_ORG_HIERARCHY AS ORG ON A.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    INNER JOIN VT_STG_JOB_PROFILE AS J ON A.JOB_ID = J.JOB_CODE
WHERE
    A.POSITION_ID IN (
        SELECT
            POSITION_ID
        FROM
            VT_HRA_RR_POSITIONS
    )
    AND CASE
        WHEN A.EMPLOYMENT_STATUS = 'Terminated' THEN 'R'
        WHEN A.EMPLOYMENT_STATUS = 'Active' THEN 'A'
        ELSE 'R'
    END = 'A';

INSERT INTO
    VT_ADGRP_NTID (ADGRP_ID, NTID)
SELECT
    DISTINCT ADGRP_ID,
    NTID
FROM
    (
        SELECT
            *
        FROM
            `gcp-project.HRA_CORE_V.HRA_PROC_ADGRP_MANUALUSERS`
    ) AS A
WHERE
    ACTION_IND = 'A'
    AND Row_Number() Over(
        PARTITION BY
            NTID,
            ADGRP_ID
        ORDER BY
            LOAD_DTTM DESC
    ) = 1;

/*CREATE MULTISET VOLATILE TABLE VT_STG_EMPLOYEE_OLD AS
 (SELECT * FROM HRA_STG_WORKDAY_V.STG_EMPLOYEE
QUALIFY Row_Number() Over(PARTITION BY EMPLOYEE_ID ORDER BY SOURCE_FILE_DTTM ASC) = 1
) WITH DATA PRIMARY INDEX(EMPLOYEE_ID)
ON COMMIT PRESERVE ROWS;

CREATE MULTISET VOLATILE TABLE VT_STG_EMPLOYEE_NEW AS
 (SELECT * FROM HRA_STG_WORKDAY_V.STG_EMPLOYEE
QUALIFY Row_Number() Over(PARTITION BY EMPLOYEE_ID ORDER BY SOURCE_FILE_DTTM DESC) = 1
) WITH DATA PRIMARY INDEX(EMPLOYEE_ID)
ON COMMIT PRESERVE ROWS;*/
DELETE FROM `gcp-project.HRA_CORE_T.ASSOCIATE_ADGROUP_ANOMALY_SNAPSHOT` WHERE TRUE;

INSERT INTO
    `gcp-project.HRA_CORE_T.ASSOCIATE_ADGROUP_ANOMALY_SNAPSHOT` (
        ASSOC_USER_NAME,
        ASSOC_ADGROUP_ID,
        EMPLOYEE_ID,
        LEGAL_FIRST_NAME,
        LEGAL_MIDDLE_NAME,
        LEGAL_LAST_NAME,
        EMPLOYMENT_STATUS,
        HIRE_DATE,
        TERM_DATE,
        FUNCTIONAL_GROUP_NAME,
        JOB_TITLE,
        SNAPSHOT_DATE
    )
SELECT
    A.ASSOC_USER_NAME,
    A.ASSOC_ADGROUP_ID,
    /*C.NTID AS OLDNTID,
    D.NTID AS NEWNTID,
    CASE WHEN A.ASSOC_USER_NAME <> C.NTID THEN 1
    WHEN A.ASSOC_USER_NAME <> D.NTID THEN 1
    ELSE 0 END,*/
    B.EMPLOYEE_ID,
    B.LEGAL_FIRST_NAME,
    B.LEGAL_MIDDLE_NAME,
    B.LEGAL_LAST_NAME,
    B.EMPLOYMENT_STATUS,
    B.HIRE_DATE,
    CASE
        WHEN B.HIRE_DATE < B.TERMINATION_DATE THEN B.TERMINATION_DATE
    END AS TERM_DATE,
    ORG.FUNCTIONAL_GROUP_NAME,
    --ORG.FUNCTIONAL_GROUP_ID
    J.JOB_TITLE,
    CURRENT_DATE AS SNAPSHOT_DATE
FROM
    (
        SELECT
            DISTINCT TRIM(ASSOC_USER_NAME) AS ASSOC_USER_NAME,
            TRIM(ASSOC_ADGROUP_ID) AS ASSOC_ADGROUP_ID
        FROM
            `gcp-project.HRA_CORE_V.ASSOCIATE_ADGROUP_SNAPSHOT`
        EXCEPT DISTINCT
        SELECT
            DISTINCT TRIM(NTID) AS ASSOC_USER_NAME,
            TRIM(ADGRP_ID) AS ASSOC_ADGROUP_ID
        FROM
            VT_ADGRP_NTID
    ) AS A
    LEFT OUTER JOIN (
        SELECT
            *
        FROM
            `gcp-project.HRA_STG_WORKDAY_V.STG_EMPLOYEE`
    ) AS B ON A.ASSOC_USER_NAME = B.NTID
    LEFT OUTER JOIN VT_STG_ORG_HIERARCHY AS ORG ON B.SUPERVISORY_ORGANIZATION_ID = ORG.SUPERVISORY_ORGANIZATION_ID
    LEFT OUTER JOIN VT_STG_JOB_PROFILE AS J ON B.JOB_ID = J.JOB_CODE
    /*LEFT OUTER JOIN VT_STG_EMPLOYEE_OLD  C
    ON C.EMPLOYEE_ID = B.EMPLOYEE_ID

    LEFT OUTER JOIN  VT_STG_EMPLOYEE_NEW  D
    ON D.EMPLOYEE_ID = B.EMPLOYEE_ID*/
WHERE
    Row_Number() Over(
        PARTITION BY
            NTID
        ORDER BY
            SOURCE_FILE_DTTM DESC
    ) = 1;

--- TEMP TABLE CLEANUP
DROP TABLE VT_STG_EMPLOYEE;
DROP TABLE VT_STG_ORG_HIERARCHY;
DROP TABLE VT_STG_JOB_PROFILE;
DROP TABLE VT_ADGRP_NTID;
DROP TABLE VT_EMP_HRCY_Piteam;
DROP TABLE VT_TMP_ORG;
DROP TABLE VT_HRA_PAI_ORG;
DROP TABLE VT_HRA_PAI_ORG_AVOID;
DROP TABLE VT_HRAPAI_POSITIONS;
DROP TABLE VT_HRA_COMMISSIONS_ORG;
DROP TABLE VT_L1_MANAGER_PSTN_ID_COMMISSIONS;
DROP TABLE VT_CTE1;
DROP TABLE VT_CTE2;
DROP TABLE VT_HRA_BENEFITS_ORG;
DROP TABLE VT_HRA_DITEAM_ORG;
DROP TABLE VT_HRA_HROPS_ORG;
DROP TABLE VT_HRA_PAYROLL_ORG;
DROP TABLE VT_HRA_PAYROLL_POSITIONS;
DROP TABLE VT_HRA_CARE_LD_ORG;
DROP TABLE VT_HRA_ELS_SUPPORT_TEAM_ORG;
DROP TABLE VT_HRA_HRFIN_ORG;
DROP TABLE VT_HRA_LOATEAM;
DROP TABLE VT_HRA_IRISK;
DROP TABLE VT_HRA_HRTALENT_ORG;
DROP TABLE VT_HRA_HRSEV_ORG;
DROP TABLE VT_HRA_CGSO_ORG;
DROP TABLE VT_ResourcePlanning;
DROP TABLE VT_HRA_HRSRPLUS;
DROP TABLE VT_EMP_HRA_HRSRPLUS;
DROP TABLE VT_HRA_RR;
DROP TABLE VT_HRA_RR_POSITIONS;
