
config {
    type: "table",
    name: "RiteWorkorderPart",
    schema: "RITE_SRC",
    description: "Mapping document for RiteWorkorderPart",
    tags: ["source", "rite"],
    assertions: {
        uniqueKey: ["PrimaryKey"]
    }
}

SELECT
    concat(coalesce(SRCWO.WO_ID, 0), '&', coalesce(SRCWOA.ASSET_SN_ID, 0), '&', coalesce(SRCWOAPARTS.PART_ID, 0)) AS PrimaryKey,
    SRCWO.WO_ID AS WorkorderNum_WO_ID,
    SRCWOA.ASSET_SN_ID AS EquipmentSNId_ASSET_SN_ID,
    SRCWOAPARTS.PART_ID AS PartId_PART_ID,
    SRCWOA.STATUS AS WorkorderStatus_STATUS,
    SRCWOAPARTS.PART_NO AS PartNumber_PART_NO,
    SRCWOAPARTS.UNIT_PRICE AS UnitPrice_UNIT_PRICE,
    SRCWOAPARTS.QUANTITY AS PartQuantity_QUANTITY,
    SRCWOA.ASSET_CODE AS EquipmentType_ASSET_CODE,
    SRCWOA.SERIAL_NO AS EquipmentSerialNumber_SERIAL_NO,
    SRCWOA.WO_DATE AS WorkorderDate_WO_DATE,
    SRCWO.WO_TYPE AS WorkorderType_WO_TYPE,
    SRCWO.ACC_UNIT AS AccountUnit_ACC_UNIT,
    CURRENT_TIMESTAMP() AS UPDATED_DATETIME,
    "a2r-data-product-dataform : RiteWorkorderPart.sqlx" AS UPDATED_BY,
    CURRENT_TIMESTAMP() AS CREATED_DATETIME,
    "a2r-data-product-dataform : RiteWorkorderPart.sqlx" AS CREATED_BY
FROM
    ${ref("TBLWORKORDER")} AS SRCWO
LEFT JOIN
    ${ref("TBLWORKORDERASSET")} AS SRCWOA ON SRCWO.WO_ID = SRCWOA.WO_ID
LEFT JOIN
    ${ref("TBLFLEETASSET")} AS SRCTBLFA ON upper(SRCTBLFA.ASSET_CODE) = upper(SRCWOA.ASSET_CODE) AND upper(SRCTBLFA.SERIAL_NO) = upper(SRCWOA.SERIAL_NO)
LEFT JOIN
    ${ref("TBLWORKORDERASSETPARTS")} AS SRCWOAPARTS ON SRCWOA.wo_id = SRCWOAPARTS.WO_ID