-- TR-GRD-001: DDL script to create the audit log table.
-- This table supports the logging requirement specified in the TRD.
-- It is assumed the GRADES_APP schema exists and the executing user has CREATE TABLE privileges.

CREATE TABLE GRADES_APP.GRADE_AUDIT_LOG (
    log_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    log_timestamp    TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
    input_mark       NUMBER(5, 2),
    calculated_grade VARCHAR2(20),
    error_message    VARCHAR2(4000),
    CONSTRAINT pk_grade_audit_log PRIMARY KEY (log_id)
);

COMMENT ON TABLE GRADES_APP.GRADE_AUDIT_LOG IS 'Auditing table for grade calculation events as per TRD-GRD-001.';
COMMENT ON COLUMN GRADES_APP.GRADE_AUDIT_LOG.log_id IS 'Primary key for the log entry.';
COMMENT ON COLUMN GRADES_APP.GRADE_AUDIT_LOG.log_timestamp IS 'Timestamp when the grade calculation was invoked.';
COMMENT ON COLUMN GRADES_APP.GRADE_AUDIT_LOG.input_mark IS 'The numerical mark provided as input to the calculation.';
COMMENT ON COLUMN GRADES_APP.GRADE_AUDIT_LOG.calculated_grade IS 'The academic grade determined by the function.';
COMMENT ON COLUMN GRADES_APP.GRADE_AUDIT_LOG.error_message IS 'Details of any exception that occurred during execution.';