CREATE SCHEMA IF NOT EXISTS `gcp-project-id.HRA_CORE_V`;
CREATE SCHEMA IF NOT EXISTS `gcp-project-id.IDW_TD_ETL_CTL_V`;

CREATE TABLE IF NOT EXISTS `gcp-project-id.HRA_CORE_V.EXPERIENCE` (
  CANDIDATE_ID STRING,
  SRC_FILE_DTTM TIMESTAMP,
  MOST_RCNT_IND STRING,
  CURR_IND STRING,
  EFF_END_DTTM TIMESTAMP,
  UPDT_PRCS_ID INT64,
  UPDT_DTTM TIMESTAMP
)
CLUSTER BY CANDIDATE_ID;

CREATE TABLE IF NOT EXISTS `gcp-project-id.IDW_TD_ETL_CTL_V.ETLCDCDATES` (
  ProcessID INT64,
  ExtractEndDttm TIMESTAMP,
  JOBNAME STRING
);