-- SCHEMA MIGRATION
CREATE SCHEMA IF NOT EXISTS `gcp-project-id.HRA_CORE_S`;
CREATE SCHEMA IF NOT EXISTS `gcp-project-id.HRA_CORE_T`;
CREATE SCHEMA IF NOT EXISTS `gcp-project-id.HRA_CORE_V`;
CREATE SCHEMA IF NOT EXISTS `gcp-project-id.HRA_SEMANTIC_S`;
CREATE SCHEMA IF NOT EXISTS `gcp-project-id.HRA_SEMANTIC_V`;

CREATE TABLE IF NOT EXISTS `gcp-project-id.HRA_CORE_T.ASSOCIATE_ADGROUP_SNAPSHOT` (
    SNAPSHOT_DT DATE NOT NULL OPTIONS(description="Snapshot date for the adgroup association."),
    ASSOC_CID STRING OPTIONS(description="Associate corporate ID."),
    ADGROUP_NM STRING OPTIONS(description="Active Directory group name."),
    LOAD_DTTM TIMESTAMP OPTIONS(description="Load timestamp.")
)
PARTITION BY SNAPSHOT_DT;

CREATE TABLE IF NOT EXISTS `gcp-project-id.HRA_CORE_T.HRA_PROC_ADGRP_MANUALUSERS` (
    MANUAL_USER_SID STRING NOT NULL OPTIONS(description="Manual user SID."),
    ASSOC_CID STRING OPTIONS(description="Associate corporate ID."),
    ADGROUP_NM STRING OPTIONS(description="Active Directory group name."),
    SRC_SYS_ID STRING OPTIONS(description="Source system ID."),
    CURR_IND STRING OPTIONS(description="Current indicator."),
    LOAD_DTTM TIMESTAMP OPTIONS(description="Load timestamp.")
);

CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.EMPLOYEE_DATA` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.ASSOCIATE` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.EM_SECONDARY_PERSONAL_DETAIL` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.ORGANIZATION_RELATION` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.JOB` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.ASSOCIATE_DETAIL` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.ASSOCIATE_EMPLOYMENT` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.ASSOCIATE_LABOR_FINANCIAL_PLAN` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.LKP_MAPPINGS` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.LOCATION` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.ORG_LEADER` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.PHYSICAL_ADDRESS` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.LKP_MAPPINGS_WS` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.ASSOCIATE_TRANSACTIONS` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.CUSTOM_ORG_REFERENCE` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_SEMANTIC_S.EMPLOYEE_MASTER_NOVOLT` AS SELECT 'base_table_stub' AS stub;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_S.ASSOCIATE_ADDITIONAL_IDS` AS SELECT 'base_table_stub' AS stub;

CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.S_EMPLOYEE_DATA` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.EMPLOYEE_DATA`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.ASSOCIATE` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.ASSOCIATE`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.EM_SECONDARY_PERSONAL_DETAIL` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.EM_SECONDARY_PERSONAL_DETAIL`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.ORGANIZATION_RELATION` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.ORGANIZATION_RELATION`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.JOB` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.JOB`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.ASSOCIATE_DETAIL` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.ASSOCIATE_DETAIL`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.ASSOCIATE_EMPLOYMENT` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.ASSOCIATE_EMPLOYMENT`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.ASSOCIATE_LABOR_FINANCIAL_PLAN` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.ASSOCIATE_LABOR_FINANCIAL_PLAN`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.LKP_MAPPINGS` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.LKP_MAPPINGS`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.LOCATION` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.LOCATION`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.ORG_LEADER` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.ORG_LEADER`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.PHYSICAL_ADDRESS` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.PHYSICAL_ADDRESS`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.LKP_MAPPINGS_WS` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.LKP_MAPPINGS_WS`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.ASSOCIATE_TRANSACTIONS` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.ASSOCIATE_TRANSACTIONS`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.CUSTOM_ORG_REFERENCE` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.CUSTOM_ORG_REFERENCE`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_SEMANTIC_V.EMPLOYEE_MASTER_NOVOLT` AS SELECT * FROM `gcp-project-id.HRA_SEMANTIC_S.EMPLOYEE_MASTER_NOVOLT`;
CREATE OR REPLACE VIEW `gcp-project-id.HRA_CORE_V.ASSOCIATE_ADDITIONAL_IDS` AS SELECT * FROM `gcp-project-id.HRA_CORE_S.ASSOCIATE_ADDITIONAL_IDS`;