CREATE OR REPLACE VIEW `gcp-project-id.HRA_SEMANTIC_V.S_EMPLOYEE_DATA_WORKDAY` AS
SELECT
  A.ASSOC_CID,
  A.LEGAL_FIRST_NM,
  A.LEGAL_LAST_NM,
  J.JOB_TITLE,
  L.LOCATION_NM
FROM
  `gcp-project-id.HRA_CORE_V.ASSOCIATE` AS A
JOIN
  `gcp-project-id.HRA_CORE_V.JOB` AS J
  ON A.ASSOC_ID = J.ASSOC_ID
JOIN
  `gcp-project-id.HRA_CORE_V.LOCATION` AS L
  ON J.LOCATION_ID = L.LOCATION_ID;